const fs = require('fs');
const data = JSON.parse(fs.readFileSync('/tmp/repo-actions-state.json', 'utf8'));
const r = data.data.repository;
console.log('name:', r.name);
console.log('description:', r.description);
console.log('pushedAt:', r.pushedAt, 'updatedAt:', r.updatedAt);
console.log('stars:', r.stargazerCount, 'forks:', r.forkCount);
console.log('isArchived:', r.isArchived, 'hasIssuesEnabled:', r.hasIssuesEnabled);
console.log('license:', r.licenseInfo);
console.log('topics:', r.repositoryTopics.nodes.map(n => n.topic.name).join(','));
console.log('---STRUCTURAL FILES---');
console.log('LICENSE:', r.license);
console.log('SECURITY.md:', r.security);
console.log('CONTRIBUTING.md:', r.contributing);
console.log('CODE_OF_CONDUCT.md:', r.coc);
console.log('dependabot.yml:', r.dependabot);
console.log('issueTemplates:', r.issueTemplates);
console.log('CI tree:', r.ciTree);
console.log('CLAUDE.md present:', !!r.claude, r.claude ? '(' + r.claude.text.length + ' bytes)' : '');
console.log('README.md byteSize:', r.readme && r.readme.byteSize);
console.log('ROADMAP:', !!r.roadmap, 'CHANGELOG:', !!r.changelog, 'TODO.md:', !!r.todoFile);
console.log('package.json:', !!r.pkgJson, 'pyproject:', !!r.pyproject, 'Cargo.toml:', !!r.cargoToml, 'go.mod:', !!r.goMod);
console.log('---OPEN ISSUES---', 'count:', r.issues.totalCount);
r.issues.nodes.forEach(i => console.log(`#${i.number} | ${i.title} | labels: ${i.labels.nodes.map(l => l.name).join(',')} | upd: ${i.updatedAt} | comments: ${i.comments.totalCount}`));
console.log('---OPEN PRS---', 'count:', r.pullRequests.totalCount);
r.pullRequests.nodes.forEach(p => console.log(`#${p.number} | ${p.title} | ${p.author?.login || '?'} | created: ${p.createdAt} | upd: ${p.updatedAt} | draft=${p.isDraft} | branch=${p.headRefName}`));
console.log('---RECENT COMMITS (top 30)---');
r.defaultBranchRef.target.history.nodes.forEach(c => console.log(`${c.committedDate} ${c.oid.slice(0,7)} ${c.messageHeadline}`));
console.log('---CLOSED ISSUES (recent 20)---');
r.closedIssues.nodes.forEach(i => console.log(`#${i.number} ${i.closedAt}: ${i.title}`));
console.log('---MERGED PRS (recent 20)---');
r.mergedPRs.nodes.forEach(p => console.log(`#${p.number} ${p.mergedAt}: ${p.title}`));
